CREATE DATABASE IF NOT EXISTS questao6;
USE questao6;
CREATE TABLE IF NOT EXISTS Students (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(20),
  value INT,
  PRIMARY KEY(id)
);
CREATE TABLE IF NOT EXISTS Notes (
  Grade INT NOT NULL AUTO_INCREMENT,
  Min_Value INT,
  Max_Value INT,
  PRIMARY KEY(Grade)
);
